### ISSUE TITLE
hexo-word-count depends on GLIBC version mismatch with Vercel environment

### ISSUE THREAD

**Issue by tisonkun** [tisonkun/blog#105]
```

ERROR Plugin load failed: hexo-word-counter
--
22:57:08.970 | Error: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /vercel/path0/node_modules/hexo-word-counter/index.node)
22:57:08.970 | at Module._extensions..node (node:internal/modules/cjs/loader:1340:18)
22:57:08.970 | at Module.load (node:internal/modules/cjs/loader:1119:32)
22:57:08.970 | at Module._load (node:internal/modules/cjs/loader:960:12)
22:57:08.970 | at Module.require (node:internal/modules/cjs/loader:1143:19)
22:57:08.970 | at req (/vercel/path0/node_modules/hexo/lib/hexo/index.js:292:23)
22:57:08.970 | at /vercel/path0/node_modules/hexo-word-counter/index.js:6:23
22:57:08.971 | at /vercel/path0/node_modules/hexo/lib/hexo/index.js:305:14
22:57:08.971 | at tryCatcher (/vercel/path0/node_modules/bluebird/js/release/util.js:16:23)
22:57:08.971 | at Promise._settlePromiseFromHandler (/vercel/path0/node_modules/bluebird/js/release/promise.js:547:31)
22:57:08.976 | at Promise._settlePromise (/vercel/path0/node_modules/bluebird/js/release/promise.js:604:18)
22:57:08.977 | at Promise._settlePromise0 (/vercel/path0/node_modules/bluebird/js/release/promise.js:649:10)
22:57:08.977 | at Promise._settlePromises (/vercel/path0/node_modules/bluebird/js/release/promise.js:729:18)
22:57:08.977 | at _drainQueueStep (/vercel/path0/node_modules/bluebird/js/release/async.js:93:12)
22:57:08.977 | at _drainQueue (/vercel/path0/node_modules/bluebird/js/release/async.js:86:9)
22:57:08.977 | at Async._drainQueues (/vercel/path0/node_modules/bluebird/js/release/async.js:102:5)
22:57:08.978 | at Async.drainQueues [as _onImmediate] (/vercel/path0/node_modules/bluebird/js/release/async.js:15:14)


```

**Comment by tisonkun** [comment]
Drop the dep in 5004e5f92539d07b01dd749e5735af9c39cac626 for now.
